packages:
  - api
catalog:
  "@eslint/compat": ^1.2.5
  "@eslint/js": ^9.18.0
  "@nestjs/cli": ^10.4.9
  "@nestjs/common": ^10.4.15
  "@nestjs/core": ^10.4.15
  "@nestjs/mapped-types": ^2.0.6
  "@nestjs/platform-express": ^10.4.15
  "@nestjs/schematics": ^10.2.3
  "@nestjs/swagger": ^8.1.1
  "@nestjs/testing": ^10.4.15
  "@prisma/client": 6.2.1
  "@types/express": ^5.0.0
  "@types/jest": ^29.5.14
  "@types/node": ^22.10.6
  "@types/supertest": ^6.0.2
  "@typescript-eslint/eslint-plugin": ^8.20.0
  "@typescript-eslint/parser": ^8.20.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  concurrently: ^9.1.2
  eslint: ^9.18.0
  eslint-config-prettier: ^10.0.1
  eslint-plugin-prettier: ^5.2.1
  husky: ^9.1.7
  jest: ^29.7.0
  jiti: ^2.4.2
  nestjs-prisma: ^0.24.0
  nodemon: ^3.1.9
  prettier: ^3.4.2
  prisma: ^6.2.1
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  swagger-ui-express: ^5.0.1
  swc: ^1.0.11
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  typescript: ^5.7.3
  typescript-eslint: ^8.20.0
