name: rrss-backend
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "3001:5432"

volumes:
  postgres:
